version: 0.2

phases:
  pre_build:
    commands:
      - echo Build SAM package
      - pwd
      - aws cloudformation package --template-file cld-ri-src.yaml --s3-bucket cld-ri-packages --output-template-file cld-ri.yaml
  build:
    commands:
      - echo Build the package
  post_build:
    commands:
      - echo Post build
      - aws cloudformation deploy --template-file cld-ri.yaml --stack-name cld-ri-stack --capabilities CAPABILITY_IAM      